Applications/Applications.WebClient/Controllers/TransactionController.cs
using Common.Utils.Exceptions;
using Core.ApplicationServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Applications.WebbClient.Controllers
{
    public class TransactionController : Controller
    {
        private readonly TransactionService TransactionService;
        private readonly ILogger<TransactionController> Logger;
        private readonly string BasicErrorMessage = "Something went wrong :/";

        public TransactionController(TransactionService transactionService,
            ILogger<TransactionController> logger)
        {
            TransactionService = transactionService;
            Logger = logger;
        }


        [HttpGet]
        public async Task<IActionResult> Transactions(string walletId, DateTime? date)
        {
            try
            {
                var transactions = await TransactionService.GetTransactionsByWalletIdAndDate(walletId, date);

                TempData["WalletId"] = walletId;
                return View(transactions);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, ex.Message);
                if (ex is EstimationPracticeException e) TempData["Error"] = e.EstimationPracticeExceptionMessage;
                else TempData["Error"] = BasicErrorMessage;

                return View();
            }
        }
    }
}

Applications/Applications.WebClient/Controllers/WalletController.cs
using Common.Utils.Exceptions;
using Core.ApplicationServices;
using Core.ApplicationServices.DTOs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Threading.Tasks;

namespace Applications.WebbClient.Controllers
{
    public class WalletController : Controller
    {
        private readonly WalletService WalletService;
        private readonly ILogger<WalletController> Logger;
        private readonly string BasicErrorMessage = "Something went wrong :/";

        public WalletController(WalletService walletService,
            ILogger<WalletController> logger)
        {
            WalletService = walletService;
            Logger = logger;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(WalletDTO walletDTO)
        {
            try
            {
                var wallet = await WalletService.CreateWallet(walletDTO);

                return RedirectToAction("WalletInfo", new { jmbg = wallet.JMBG, pass = wallet.PASS });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, ex.Message);
                if (ex is EstimationPracticeException e) TempData["Error"] = e.EstimationPracticeExceptionMessage;
                else TempData["Error"] = BasicErrorMessage;

                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> WalletInfo(string jmbg, string pass)
        {

            try
            {
                var wallet = await WalletService.GetWallet(jmbg, pass);

                return View(wallet);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, ex.Message);
                if (ex is EstimationPracticeException e) TempData["Error"] = e.EstimationPracticeExceptionMessage;
                else TempData["Error"] = BasicErrorMessage;

                return View();
            }
        }

        [HttpGet]
        public IActionResult Deposit()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Deposit(string jmbg, string pass, decimal amount)
        {

            try
            {
                var wallet = await WalletService.Deposit(jmbg, pass, amount);

                TempData["Success"] = "Money is successfully added!";
                return RedirectToAction("WalletInfo", new { jmbg = wallet.JMBG, pass = wallet.PASS });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, ex.Message);
                if (ex is EstimationPracticeException e) TempData["Error"] = e.EstimationPracticeExceptionMessage;
                else TempData["Error"] = BasicErrorMessage;

                return View();
            }
        }

        [HttpGet]
        public IActionResult Withdraw()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Withdraw(string jmbg, string pass, decimal amount)
        {

            try
            {
                var wallet = await WalletService.Withdraw(jmbg, pass, amount);

                TempData["Success"] = "Money is successfully withdrawed!";
                return RedirectToAction("WalletInfo", new { jmbg = wallet.JMBG, pass = wallet.PASS });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, ex.Message);
                if (ex is EstimationPracticeException e) TempData["Error"] = e.EstimationPracticeExceptionMessage;
                else TempData["Error"] = BasicErrorMessage;

                return View();
            }
        }

        [HttpGet]
        public IActionResult Transfer()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Transfer(string jmbg, string relatedJmbg, string pass, decimal amount)
        {

            try
            {
                var wallet = await WalletService.Transfer(jmbg, relatedJmbg, pass, amount);

                TempData["Success"] = "Money is successfully transfered!: " + amount;
                return RedirectToAction("WalletInfo", new { jmbg = wallet.JMBG, pass = wallet.PASS });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, ex.Message);
                if (ex is EstimationPracticeException e) TempData["Error"] = e.EstimationPracticeExceptionMessage;
                else TempData["Error"] = BasicErrorMessage;

                return View();
            }
        }

        [HttpGet]
        public IActionResult AdminPanel(string pass) 
        {
            if (!AdminRoleHelper.IsAdmin(pass))
            {
                TempData["Error"] = "U are not admin!";
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> BlockWallet(string pass, string jmbg)
        {
            if (!AdminRoleHelper.IsAdmin(pass))
            {
                TempData["Error"] = "U are not admin!";
                return RedirectToAction("Index", "Home");
            }

            try
            {
                var wallet = await WalletService.BlockWallet(jmbg);

                TempData["Success"] = "Wallet is successfully blocked!";
                return RedirectToAction("AdminPanel", new { pass = pass });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, ex.Message);
                if (ex is EstimationPracticeException e) TempData["Error"] = e.EstimationPracticeExceptionMessage;
                else TempData["Error"] = BasicErrorMessage;

                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> UnBlockWallet(string pass, string jmbg)
        {
            if (!AdminRoleHelper.IsAdmin(pass))
            {
                TempData["Error"] = "U are not admin!";
                return RedirectToAction("Index", "Home");
            }

            try
            {
                var wallet = await WalletService.UnBlockWallet(jmbg);

                TempData["Success"] = "Wallet is successfully unblocked!";
                return RedirectToAction("AdminPanel", new { pass = pass });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, ex.Message);
                if (ex is EstimationPracticeException e) TempData["Error"] = e.EstimationPracticeExceptionMessage;
                else TempData["Error"] = BasicErrorMessage;

                return View();
            }
        }

        [HttpGet]
        public async Task<IActionResult> UpdatePass()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> UpdatePass(string pass, string jmbg, string newPass)
        {
            try
            {
                var wallet = await WalletService.UpdatePass(pass, jmbg, newPass);

                TempData["Success"] = "Your pass is updated successfully!";
                return RedirectToAction("WalletInfo", new { jmbg = wallet.JMBG, pass = wallet.PASS });
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, ex.Message);
                if (ex is EstimationPracticeException e) TempData["Error"] = e.EstimationPracticeExceptionMessage;
                else TempData["Error"] = BasicErrorMessage;

                return View();
            }
        }
        
    }
}

Applications/Applications.WebClient/Views/Wallet/AdminPanel.cshtml
<section class="page-section" id="transfer">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Admin panel</h2>
            <h3 class="section-subheading text-muted">From wallet, to your bank account. Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <form method="post">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <input autocomplete="off" class="form-control" id="JMBG" name="JMBG" placeholder="JMBG to block*" required="required" data-validation-required-message="Please enter JMBG to block." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group">
                        <input autocomplete="off" class="form-control" id="PASS" name="Pass" placeholder="Your Pass *" required="required" data-validation-required-message="Please enter your Pass." />
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
            </div>
            <div>
                <div id="success"></div>
                <button class="btn btn-primary btn-xl text-uppercase" type="submit" asp-action="BlockWallet">Block wallet</button>
            </div>
        </form>
        <br />
        <br />
        <br />
        <form method="post">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <input autocomplete="off" class="form-control" id="JMBG" name="JMBG" placeholder="JMBG to unblock*" required="required" data-validation-required-message="Please enter JMBG to unblock." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group">
                        <input autocomplete="off" class="form-control" id="PASS" name="Pass" placeholder="Your Pass *" required="required" data-validation-required-message="Please enter your Pass." />
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
            </div>
            <div>
                <div id="success"></div>
                <button class="btn btn-primary btn-xl text-uppercase" type="submit" asp-action="UnBlockWallet">Unblock wallet</button>
            </div>
        </form>
    </div>
</section>

Applications/Applications.WebClient/Views/Wallet/Create.cshtml
<section class="page-section" id="createWallet">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Already have a wallet?</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <form>
            <div class="row align-items-stretch mb-5">
                <button class="btn-sm btn-info" type="button" onclick="FillJmbgAndPassFromLocalStorage()">Apply saved jmbg & pass</button>
                <div class="col-md-6">
                    <div class="form-group">
                        <input autocomplete="off" class="form-control" id="JMBG" name="JMBG" placeholder="Your JMBG *" required="required" data-validation-required-message="Please enter your JMBG." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group">
                        <input autocomplete="off" class="form-control" id="PASS" name="Pass" placeholder="Your Pass *" required="required" data-validation-required-message="Please enter your Pass." />
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <button class="btn btn-primary btn-xl text-uppercase" type="submit" asp-action="WalletInfo">Wallet details</button>
            </div>
        </form>
        <br />
        <br />
        <br />
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Create wallet</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <form method="post">
            <div class="row align-items-stretch mb-5">
                <div class="col-md-6">
                    <div class="form-group">
                        <input class="form-control" id="FirstName" name="FirstName" type="text" placeholder="Your Name *" required="required" data-validation-required-message="Please enter your name." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group">
                        <input class="form-control" id="LastName" name="LastName" type="text" placeholder="Your Last Name *" required="required" data-validation-required-message="Please enter your last name." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group">
                        <input  autocomplete="off" class="form-control" id="JMBG" name="JMBG" placeholder="Your JMBG *" required="required" data-validation-required-message="Please enter your JMBG." />
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group mb-md-0">
                        <input class="form-control" id="Bank" name="Bank" placeholder="Your Bank Name *" required="required" data-validation-required-message="Please enter Bank Name." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group mb-md-0">
                        <input autocomplete="off" class="form-control" id="PIN" name="PIN" placeholder="Your PIN *" required="required" data-validation-required-message="Please enter PIN." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group mb-md-0">
                        <input class="form-control" id="PIN" name="BankAccount" placeholder="Your Bank Account *" required="required" data-validation-required-message="Please enter Bank Account." />
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <div id="success"></div>
                <button class="btn btn-primary btn-xl text-uppercase" type="submit" asp-action="Create">Create wallet</button>
            </div>
        </form>
    </div>
</section>

Applications/Applications.WebClient/Views/Wallet/Deposit.cshtml
<section class="page-section" id="deposit">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Add money from bank</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <form method="post">
            <div class="row align-items-stretch mb-5">
                <button class="btn-sm btn-info" type="button" onclick="FillJmbgAndPassFromLocalStorage()">Apply saved jmbg & pass</button>
                <div class="col-md-6">
                    <div class="form-group">
                        <input  autocomplete="off" class="form-control" id="JMBG" name="JMBG" placeholder="Your JMBG *" required="required" data-validation-required-message="Please enter your JMBG." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group">
                        <input  autocomplete="off" class="form-control" id="PASS" name="Pass" placeholder="Your Pass *" required="required" data-validation-required-message="Please enter your Pass." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group">
                        <input class="form-control" id="Amount" name="Amount" placeholder="Enter amount *" required="required" data-validation-required-message="Please enter amount." />
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <div id="success"></div>
                <button class="btn btn-primary btn-xl text-uppercase" type="submit" asp-action="Deposit">Add money</button>
            </div>
        </form>
    </div>
</section>

Applications/Applications.WebClient/Views/Wallet/Transfer.cshtml
<section class="page-section" id="transfer">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Transfer money</h2>
            <h3 class="section-subheading text-muted">From wallet, to your bank account. Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <form method="post">
            <div class="row align-items-stretch mb-5">
                <button class="btn-sm btn-info" type="button" onclick="FillJmbgAndPassFromLocalStorage()">Apply saved jmbg & pass</button>
                <div class="col-md-6">
                    <div class="form-group">
                        <input autocomplete="off" class="form-control" id="JMBG" name="JMBG" placeholder="Your JMBG *" required="required" data-validation-required-message="Please enter your JMBG." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group">
                        <input autocomplete="off" class="form-control" 
                               id="relatedJmbg" 
                               name="relatedJmbg" 
                               placeholder="JMBG of account you are sending to*" 
                               required="required" 
                               data-validation-required-message="Please enter JMBG." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group">
                        <input autocomplete="off" class="form-control" id="PASS" name="Pass" placeholder="Your Pass *" required="required" data-validation-required-message="Please enter your Pass." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group">
                        <input class="form-control" id="Amount" name="Amount" placeholder="Enter amount *" required="required" data-validation-required-message="Please enter amount." />
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <div id="success"></div>
                <button class="btn btn-primary btn-xl text-uppercase" type="submit" asp-action="Transfer">Transfer money</button>
            </div>
        </form>
    </div>
</section>

Applications/Applications.WebClient/Views/Wallet/UpdatePass.cshtml
<section class="page-section" id="deposit">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Add money from bank</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <form method="post">
            <div class="row align-items-stretch mb-5">
                <button class="btn-sm btn-info" type="button" onclick="FillJmbgAndPassFromLocalStorage()">Apply saved jmbg & pass</button>
                <div class="col-md-6">
                    <div class="form-group">
                        <input autocomplete="off" class="form-control"
                               id="JMBG" name="JMBG" placeholder="Your JMBG *" required="required"
                               data-validation-required-message="Please enter your JMBG." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group">
                        <input autocomplete="off" class="form-control"
                               id="PASS" name="Pass" placeholder="Your Pass *" required="required"
                               data-validation-required-message="Please enter your Pass." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group">
                        <input autocomplete="off" class="form-control"
                               id="NewPass" name="NewPass" placeholder="Your New Pass (length must be 6)*" required="required"
                               data-validation-required-message="Please enter your new Pass." />
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <div id="success"></div>
                <button class="btn btn-primary btn-xl text-uppercase" type="submit" asp-action="UpdatePass">Update pass</button>
            </div>
        </form>
    </div>
</section>

Applications/Applications.WebClient/Views/Wallet/WalletInfo.cshtml
@model Core.ApplicationServices.DTOs.WalletDTO

<section class="page-section" id="createWallet">
    <div>
        <h2 class="section-heading text-uppercase">Wallet details</h2>
        <a asp-controller="Transaction" asp-action="Transactions" asp-route-walletId="@Model.Id">VIEW TRANSACTIONS</a>
        <br />
        <a asp-controller="Wallet" asp-action="UpdatePass">UPDATE PASS</a>
        <br />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FirstName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Balance)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Balance)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.JMBG)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.JMBG)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Bank)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Bank)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PIN)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PIN)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.BankAccount)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BankAccount)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.IsBlocked)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.IsBlocked)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PASS)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PASS)
            </dd>
        </dl>
        <button class="btn btn-primary" onclick="SavePassAndJMBGToLocalStorage('@Model.PASS', '@Model.JMBG')">Save Pass & JMBG to your browser</button>
        <button class="btn btn-primary" onclick="ClearLocalStorage()">Delete Saved Pass & JMBG</button>
        <p id="pass-jmbg-saved" style="display: none">Saved successfully!</p>
    </div>


    <br />
    <br />
    <br />
    <br />
    <div style="margin-top: 20px">
        <a asp-controller="Home" asp-action="Index">Back to Home</a>
    </div>
</section>
<script>
    function SavePassAndJMBGToLocalStorage(pass, jmbg) {
        localStorage.clear();
        localStorage.setItem('pass', pass);
        localStorage.setItem('jmbg', jmbg);
        document.getElementById("pass-jmbg-saved").style.display = "block"
    }

    function ClearLocalStorage() {
        localStorage.clear();
        document.getElementById("pass-jmbg-saved").style.display = "block"
    }
</script>

Applications/Applications.WebClient/Views/Wallet/Withdraw.cshtml
<section class="page-section" id="withdraw">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Withdraw money</h2>
            <h3 class="section-subheading text-muted">From wallet, to your bank account. Lorem ipsum dolor sit amet consectetur.</h3>
        </div>
        <form method="post">
            <div class="row align-items-stretch mb-5">
                <button class="btn-sm btn-info" type="button" onclick="FillJmbgAndPassFromLocalStorage()">Apply saved jmbg & pass</button>
                <div class="col-md-6">
                    <div class="form-group">
                        <input  autocomplete="off" class="form-control" id="JMBG" name="JMBG" placeholder="Your JMBG *" required="required" data-validation-required-message="Please enter your JMBG." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group">
                        <input  autocomplete="off" class="form-control" id="PASS" name="Pass" placeholder="Your Pass *" required="required" data-validation-required-message="Please enter your Pass." />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="form-group">
                        <input class="form-control" id="Amount" name="Amount" placeholder="Enter amount *" required="required" data-validation-required-message="Please enter amount." />
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <div id="success"></div>
                <button class="btn btn-primary btn-xl text-uppercase" type="submit" asp-action="Withdraw">Withdraw money</button>
            </div>
        </form>
    </div>
</section>